// viewer/lib/supabase/types.ts
//
// 상단: Supabase CLI로 생성된 Database 타입 (supabase gen types typescript)
// 하단: 페이지/컴포넌트용 도메인 타입 (mock-data.ts, queries.ts에서 import)
//
// 재생성: npm run types  (supabase gen types typescript --linked)

// ── Generated by Supabase CLI ────────────────────────────────

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      agent_analyses: {
        Row: {
          anomaly_id: string
          created_at: string | null
          human_feedback: Json | null
          id: string
          latency_ms: number | null
          llm_reasoning: string
          model_version: string
          prompt_version: string | null
          strategy_recommendation: Json | null
          tokens_in: number | null
          tokens_out: number | null
        }
        Insert: {
          anomaly_id: string
          created_at?: string | null
          human_feedback?: Json | null
          id?: string
          latency_ms?: number | null
          llm_reasoning: string
          model_version: string
          prompt_version?: string | null
          strategy_recommendation?: Json | null
          tokens_in?: number | null
          tokens_out?: number | null
        }
        Update: {
          anomaly_id?: string
          created_at?: string | null
          human_feedback?: Json | null
          id?: string
          latency_ms?: number | null
          llm_reasoning?: string
          model_version?: string
          prompt_version?: string | null
          strategy_recommendation?: Json | null
          tokens_in?: number | null
          tokens_out?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "agent_analyses_anomaly_id_fkey"
            columns: ["anomaly_id"]
            isOneToOne: false
            referencedRelation: "anomalies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "agent_analyses_anomaly_id_fkey"
            columns: ["anomaly_id"]
            isOneToOne: false
            referencedRelation: "v_today_findings"
            referencedColumns: ["anomaly_id"]
          },
        ]
      }
      agent_analyses_feedback: {
        Row: {
          analysis_id: string
          comment: string | null
          created_at: string | null
          id: string
          user_id: string
          verdict: string
        }
        Insert: {
          analysis_id: string
          comment?: string | null
          created_at?: string | null
          id?: string
          user_id: string
          verdict: string
        }
        Update: {
          analysis_id?: string
          comment?: string | null
          created_at?: string | null
          id?: string
          user_id?: string
          verdict?: string
        }
        Relationships: [
          {
            foreignKeyName: "agent_analyses_feedback_analysis_id_fkey"
            columns: ["analysis_id"]
            isOneToOne: false
            referencedRelation: "agent_analyses"
            referencedColumns: ["id"]
          },
        ]
      }
      anomalies: {
        Row: {
          anomaly_type: string
          created_at: string | null
          detected_on: string
          evidence: Json
          id: string
          product_id: string
          severity: number
          snapshot_id: string | null
        }
        Insert: {
          anomaly_type: string
          created_at?: string | null
          detected_on: string
          evidence: Json
          id?: string
          product_id: string
          severity: number
          snapshot_id?: string | null
        }
        Update: {
          anomaly_type?: string
          created_at?: string | null
          detected_on?: string
          evidence?: Json
          id?: string
          product_id?: string
          severity?: number
          snapshot_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "anomalies_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "anomalies_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "v_today_findings"
            referencedColumns: ["product_id"]
          },
          {
            foreignKeyName: "anomalies_snapshot_id_fkey"
            columns: ["snapshot_id"]
            isOneToOne: false
            referencedRelation: "product_snapshots"
            referencedColumns: ["id"]
          },
        ]
      }
      brands: {
        Row: {
          company_id: string | null
          company_mapping_confidence: string | null
          created_at: string | null
          id: string
          is_competitor: boolean | null
          is_own: boolean | null
          musinsa_brand_id: string | null
          name: string
          notes: string | null
          slug: string
          tier: string | null
        }
        Insert: {
          company_id?: string | null
          company_mapping_confidence?: string | null
          created_at?: string | null
          id?: string
          is_competitor?: boolean | null
          is_own?: boolean | null
          musinsa_brand_id?: string | null
          name: string
          notes?: string | null
          slug: string
          tier?: string | null
        }
        Update: {
          company_id?: string | null
          company_mapping_confidence?: string | null
          created_at?: string | null
          id?: string
          is_competitor?: boolean | null
          is_own?: boolean | null
          musinsa_brand_id?: string | null
          name?: string
          notes?: string | null
          slug?: string
          tier?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "brands_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "brands_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "v_company_brand_summary"
            referencedColumns: ["id"]
          },
        ]
      }
      categories: {
        Row: {
          depth: number
          id: string
          is_active: boolean | null
          musinsa_code: string
          name_kr: string
          notes: string | null
          parent_path: string | null
        }
        Insert: {
          depth: number
          id?: string
          is_active?: boolean | null
          musinsa_code: string
          name_kr: string
          notes?: string | null
          parent_path?: string | null
        }
        Update: {
          depth?: number
          id?: string
          is_active?: boolean | null
          musinsa_code?: string
          name_kr?: string
          notes?: string | null
          parent_path?: string | null
        }
        Relationships: []
      }
      companies: {
        Row: {
          created_at: string | null
          fiscal_note: string | null
          id: string
          is_own: boolean | null
          listing_type: string
          name: string
          name_alt: string | null
          notes: string | null
          op_income_2024_mkrw: number | null
          op_income_2025_mkrw: number | null
          op_income_yoy_pct: number | null
          op_margin_2025_pct: number | null
          op_status_note: string | null
          revenue_2024_mkrw: number | null
          revenue_2025_mkrw: number | null
          revenue_yoy_pct: number | null
          source: string | null
        }
        Insert: {
          created_at?: string | null
          fiscal_note?: string | null
          id?: string
          is_own?: boolean | null
          listing_type: string
          name: string
          name_alt?: string | null
          notes?: string | null
          op_income_2024_mkrw?: number | null
          op_income_2025_mkrw?: number | null
          op_income_yoy_pct?: number | null
          op_margin_2025_pct?: number | null
          op_status_note?: string | null
          revenue_2024_mkrw?: number | null
          revenue_2025_mkrw?: number | null
          revenue_yoy_pct?: number | null
          source?: string | null
        }
        Update: {
          created_at?: string | null
          fiscal_note?: string | null
          id?: string
          is_own?: boolean | null
          listing_type?: string
          name?: string
          name_alt?: string | null
          notes?: string | null
          op_income_2024_mkrw?: number | null
          op_income_2025_mkrw?: number | null
          op_income_yoy_pct?: number | null
          op_margin_2025_pct?: number | null
          op_status_note?: string | null
          revenue_2024_mkrw?: number | null
          revenue_2025_mkrw?: number | null
          revenue_yoy_pct?: number | null
          source?: string | null
        }
        Relationships: []
      }
      company_brand_mapping_log: {
        Row: {
          brand_id: string | null
          brand_name: string | null
          brand_slug_guess: string | null
          company_name: string | null
          confidence: string | null
          created_at: string | null
          id: number
          matched: boolean | null
        }
        Insert: {
          brand_id?: string | null
          brand_name?: string | null
          brand_slug_guess?: string | null
          company_name?: string | null
          confidence?: string | null
          created_at?: string | null
          id?: number
          matched?: boolean | null
        }
        Update: {
          brand_id?: string | null
          brand_name?: string | null
          brand_slug_guess?: string | null
          company_name?: string | null
          confidence?: string | null
          created_at?: string | null
          id?: number
          matched?: boolean | null
        }
        Relationships: []
      }
      daily_reports: {
        Row: {
          created_at: string | null
          duration_ms: number | null
          finished_at: string | null
          html_url: string | null
          id: string
          notion_page_id: string | null
          report_date: string
          slack_message_ts: string | null
          stages: Json | null
          status: string | null
          top_findings: Json | null
          total_analyses: number | null
          total_anomalies: number | null
        }
        Insert: {
          created_at?: string | null
          duration_ms?: number | null
          finished_at?: string | null
          html_url?: string | null
          id?: string
          notion_page_id?: string | null
          report_date: string
          slack_message_ts?: string | null
          stages?: Json | null
          status?: string | null
          top_findings?: Json | null
          total_analyses?: number | null
          total_anomalies?: number | null
        }
        Update: {
          created_at?: string | null
          duration_ms?: number | null
          finished_at?: string | null
          html_url?: string | null
          id?: string
          notion_page_id?: string | null
          report_date?: string
          slack_message_ts?: string | null
          stages?: Json | null
          status?: string | null
          top_findings?: Json | null
          total_analyses?: number | null
          total_anomalies?: number | null
        }
        Relationships: []
      }
      own_sku_cache: {
        Row: {
          own_sku: string
          pos_price: number | null
          refreshed_at: string | null
          sales_7d: number | null
          stock_ea: number | null
        }
        Insert: {
          own_sku: string
          pos_price?: number | null
          refreshed_at?: string | null
          sales_7d?: number | null
          stock_ea?: number | null
        }
        Update: {
          own_sku?: string
          pos_price?: number | null
          refreshed_at?: string | null
          sales_7d?: number | null
          stock_ea?: number | null
        }
        Relationships: []
      }
      product_images: {
        Row: {
          cdn_url: string | null
          height: number | null
          id: string
          image_type: string | null
          order_idx: number | null
          perceptual_hash: string | null
          product_id: string
          scraped_at: string | null
          storage_path: string
          width: number | null
        }
        Insert: {
          cdn_url?: string | null
          height?: number | null
          id?: string
          image_type?: string | null
          order_idx?: number | null
          perceptual_hash?: string | null
          product_id: string
          scraped_at?: string | null
          storage_path: string
          width?: number | null
        }
        Update: {
          cdn_url?: string | null
          height?: number | null
          id?: string
          image_type?: string | null
          order_idx?: number | null
          perceptual_hash?: string | null
          product_id?: string
          scraped_at?: string | null
          storage_path?: string
          width?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "product_images_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_images_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "v_today_findings"
            referencedColumns: ["product_id"]
          },
        ]
      }
      product_matches: {
        Row: {
          competitor_product_id: string
          computed_at: string | null
          diff_summary: Json | null
          id: string
          match_basis: Json | null
          own_product_id: string | null
          own_sku: string | null
          similarity_score: number
        }
        Insert: {
          competitor_product_id: string
          computed_at?: string | null
          diff_summary?: Json | null
          id?: string
          match_basis?: Json | null
          own_product_id?: string | null
          own_sku?: string | null
          similarity_score: number
        }
        Update: {
          competitor_product_id?: string
          computed_at?: string | null
          diff_summary?: Json | null
          id?: string
          match_basis?: Json | null
          own_product_id?: string | null
          own_sku?: string | null
          similarity_score?: number
        }
        Relationships: [
          {
            foreignKeyName: "product_matches_competitor_product_id_fkey"
            columns: ["competitor_product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_matches_competitor_product_id_fkey"
            columns: ["competitor_product_id"]
            isOneToOne: false
            referencedRelation: "v_today_findings"
            referencedColumns: ["product_id"]
          },
          {
            foreignKeyName: "product_matches_own_product_id_fkey"
            columns: ["own_product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_matches_own_product_id_fkey"
            columns: ["own_product_id"]
            isOneToOne: false
            referencedRelation: "v_today_findings"
            referencedColumns: ["product_id"]
          },
        ]
      }
      product_snapshots: {
        Row: {
          current_price: number
          discount_rate: number | null
          id: string
          is_sold_out: boolean | null
          list_price: number | null
          product_id: string
          rank_main: number | null
          rank_realtime: number | null
          rank_weekly: number | null
          rating: number | null
          review_count: number | null
          scraped_at: string | null
          snapshot_date: string
          view_count_proxy: number | null
          wishlist_count: number | null
        }
        Insert: {
          current_price: number
          discount_rate?: number | null
          id?: string
          is_sold_out?: boolean | null
          list_price?: number | null
          product_id: string
          rank_main?: number | null
          rank_realtime?: number | null
          rank_weekly?: number | null
          rating?: number | null
          review_count?: number | null
          scraped_at?: string | null
          snapshot_date: string
          view_count_proxy?: number | null
          wishlist_count?: number | null
        }
        Update: {
          current_price?: number
          discount_rate?: number | null
          id?: string
          is_sold_out?: boolean | null
          list_price?: number | null
          product_id?: string
          rank_main?: number | null
          rank_realtime?: number | null
          rank_weekly?: number | null
          rating?: number | null
          review_count?: number | null
          scraped_at?: string | null
          snapshot_date?: string
          view_count_proxy?: number | null
          wishlist_count?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "product_snapshots_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "product_snapshots_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "v_today_findings"
            referencedColumns: ["product_id"]
          },
        ]
      }
      products: {
        Row: {
          brand_id: string
          category_id: string | null
          description: string | null
          embedding: string | null
          first_seen_at: string | null
          id: string
          last_updated_at: string | null
          list_price: number | null
          musinsa_no: string
          name: string
          name_en: string | null
          own_sku: string | null
          url: string
        }
        Insert: {
          brand_id: string
          category_id?: string | null
          description?: string | null
          embedding?: string | null
          first_seen_at?: string | null
          id?: string
          last_updated_at?: string | null
          list_price?: number | null
          musinsa_no: string
          name: string
          name_en?: string | null
          own_sku?: string | null
          url: string
        }
        Update: {
          brand_id?: string
          category_id?: string | null
          description?: string | null
          embedding?: string | null
          first_seen_at?: string | null
          id?: string
          last_updated_at?: string | null
          list_price?: number | null
          musinsa_no?: string
          name?: string
          name_en?: string | null
          own_sku?: string | null
          url?: string
        }
        Relationships: [
          {
            foreignKeyName: "products_brand_id_fkey"
            columns: ["brand_id"]
            isOneToOne: false
            referencedRelation: "brands"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "products_brand_id_fkey"
            columns: ["brand_id"]
            isOneToOne: false
            referencedRelation: "v_today_findings"
            referencedColumns: ["brand_id"]
          },
          {
            foreignKeyName: "products_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
        ]
      }
      promotions: {
        Row: {
          discount_amount: number | null
          discount_rate: number | null
          discovered_at: string | null
          ends_at: string | null
          final_price: number | null
          id: string
          list_price: number | null
          meta: Json | null
          product_id: string
          promo_name: string | null
          promo_type: string
          starts_at: string | null
        }
        Insert: {
          discount_amount?: number | null
          discount_rate?: number | null
          discovered_at?: string | null
          ends_at?: string | null
          final_price?: number | null
          id?: string
          list_price?: number | null
          meta?: Json | null
          product_id: string
          promo_name?: string | null
          promo_type: string
          starts_at?: string | null
        }
        Update: {
          discount_amount?: number | null
          discount_rate?: number | null
          discovered_at?: string | null
          ends_at?: string | null
          final_price?: number | null
          id?: string
          list_price?: number | null
          meta?: Json | null
          product_id?: string
          promo_name?: string | null
          promo_type?: string
          starts_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "promotions_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "promotions_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "v_today_findings"
            referencedColumns: ["product_id"]
          },
        ]
      }
      review_snapshots: {
        Row: {
          avg_rating: number | null
          cumulative_review_count: number
          id: string
          new_review_count: number | null
          product_id: string
          sentiment_summary: Json | null
          snapshot_date: string
        }
        Insert: {
          avg_rating?: number | null
          cumulative_review_count: number
          id?: string
          new_review_count?: number | null
          product_id: string
          sentiment_summary?: Json | null
          snapshot_date: string
        }
        Update: {
          avg_rating?: number | null
          cumulative_review_count?: number
          id?: string
          new_review_count?: number | null
          product_id?: string
          sentiment_summary?: Json | null
          snapshot_date?: string
        }
        Relationships: [
          {
            foreignKeyName: "review_snapshots_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "review_snapshots_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "v_today_findings"
            referencedColumns: ["product_id"]
          },
        ]
      }
      sku_actions: {
        Row: {
          anomaly_id: string
          assignee: string | null
          created_at: string | null
          created_by: string
          id: string
          kind: string
          memo: string | null
          own_sku: string
          status: string | null
          updated_at: string | null
        }
        Insert: {
          anomaly_id: string
          assignee?: string | null
          created_at?: string | null
          created_by: string
          id?: string
          kind: string
          memo?: string | null
          own_sku: string
          status?: string | null
          updated_at?: string | null
        }
        Update: {
          anomaly_id?: string
          assignee?: string | null
          created_at?: string | null
          created_by?: string
          id?: string
          kind?: string
          memo?: string | null
          own_sku?: string
          status?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sku_actions_anomaly_id_fkey"
            columns: ["anomaly_id"]
            isOneToOne: false
            referencedRelation: "anomalies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sku_actions_anomaly_id_fkey"
            columns: ["anomaly_id"]
            isOneToOne: false
            referencedRelation: "v_today_findings"
            referencedColumns: ["anomaly_id"]
          },
        ]
      }
    }
    Views: {
      v_company_brand_summary: {
        Row: {
          brand_count: number | null
          id: string | null
          is_own: boolean | null
          listing_type: string | null
          musinsa_present_count: number | null
          name: string | null
          op_margin_2025_pct: number | null
          op_status_note: string | null
        }
        Relationships: []
      }
      v_pipeline_today: {
        Row: {
          duration: string | null
          ended_at: string | null
          stage_name: string | null
          stage_order: number | null
          started_at: string | null
          status: string | null
        }
        Relationships: []
      }
      v_today_findings: {
        Row: {
          anomaly_id: string | null
          anomaly_type: string | null
          brand_id: string | null
          brand_is_own: boolean | null
          brand_name: string | null
          brand_slug: string | null
          current_price: number | null
          delta_rank_1d: number | null
          detected_on: string | null
          evidence: Json | null
          matched_sku_count: number | null
          musinsa_no: string | null
          prev_price: number | null
          prev_rank: number | null
          prev_wishlist: number | null
          product_id: string | null
          product_name: string | null
          product_url: string | null
          rank_main: number | null
          review_count: number | null
          severity: number | null
          wishlist_count: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      f_anomaly_kpis: {
        Args: { p_anomaly_id: string }
        Returns: {
          anomaly_type: string
          delta_rank_1d: number
          delta_rank_7d: number
          delta_wishlist_pct: number
          matched_sku_count: number
          rank_main: number
          review_velocity_x: number
          severity: number
          wishlist_count: number
        }[]
      }
      f_brand_trend: {
        Args: { p_brand_ids: string[]; p_days?: number; p_metric: string }
        Returns: {
          brand_id: string
          date: string
          value: number
        }[]
      }
      f_own_sku_status: {
        Args: { p_own_sku: string }
        Returns: {
          pos_price: number
          refreshed_at: string
          sales_7d: number
          stock_ea: number
          stock_tier: string
        }[]
      }
      f_product_trend: {
        Args: { p_days?: number; p_product_id: string }
        Returns: {
          current_price: number
          date: string
          discount_rate: number
          rank_main: number
          rank_realtime: number
          rating: number
          review_count: number
          wishlist_count: number
        }[]
      }
      f_severity_daily: {
        Args: { end_date: string; start_date: string }
        Returns: {
          date: string
          high: number
          low: number
          med: number
        }[]
      }
      match_own_products: {
        Args: {
          competitor_id: string
          match_count?: number
          match_threshold?: number
        }
        Returns: {
          competitor_price: number
          own_list_price: number
          own_product_id: string
          own_product_name: string
          own_sku: string
          price_diff_pct: number
          same_category: boolean
          similarity: number
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof DatabaseWithoutInternals, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const


// ── Domain types (hand-written) ──────────────────────────────
// 페이지/컴포넌트/mock-data.ts 에서 import.
// v_today_findings 뷰는 DB상 nullable이지만 inner join 보장으로
// 실제 데이터에서 핵심 필드는 항상 non-null → 도메인 타입은 non-null 유지.

export type SeverityScore = number; // 0.0 ~ 1.0
export type AnomalyType =
  | "rank_surge"
  | "price_change"
  | "review_velocity"
  | "new_entrant"
  | "promo_start"
  | "wishlist_surge";

// ── v_today_findings ────────────────────────────────────────
export interface TodayFinding {
  anomaly_id: string;
  detected_on: string;
  anomaly_type: AnomalyType;
  severity: SeverityScore;
  evidence: Record<string, unknown>;
  product_id: string;
  musinsa_no: string;
  product_name: string;
  product_url: string;
  brand_id: string;
  brand_name: string;
  brand_slug: string;
  brand_is_own: boolean;
  rank_main: number | null;
  current_price: number | null;
  wishlist_count: number | null;
  review_count: number | null;
  prev_rank: number | null;
  prev_wishlist: number | null;
  prev_price: number | null;
  delta_rank_1d: number | null;
  matched_sku_count: number;
}

// ── v_pipeline_today ────────────────────────────────────────
export interface PipelineStage {
  stage_name: string;
  status: "ok" | "running" | "pending" | "error";
  started_at: string | null;
  ended_at: string | null;
  duration: string | null;
  stage_order: number;
}

// ── f_severity_daily ────────────────────────────────────────
export interface SeverityDaily {
  date: string;
  high: number;
  med: number;
  low: number;
}

// ── f_product_trend ─────────────────────────────────────────
export interface ProductTrendRow {
  date: string;
  rank_main: number | null;
  rank_realtime: number | null;
  current_price: number | null;
  discount_rate: number | null;
  wishlist_count: number | null;
  review_count: number | null;
  rating: number | null;
}

// ── f_anomaly_kpis ──────────────────────────────────────────
export interface AnomalyKpis {
  rank_main: number | null;
  delta_rank_1d: number | null;
  delta_rank_7d: number | null;
  wishlist_count: number | null;
  delta_wishlist_pct: number | null;
  review_velocity_x: number | null;
  matched_sku_count: number;
  severity: SeverityScore;
  anomaly_type: AnomalyType;
}

// ── f_own_sku_status ────────────────────────────────────────
export interface OwnSkuStatus {
  pos_price: number | null;
  stock_ea: number | null;
  sales_7d: number | null;
  stock_tier: "low" | "mid" | "high";
  refreshed_at: string;
}

// ── product_matches (join 결과) ─────────────────────────────
export interface ProductMatch {
  id: string;
  competitor_product_id: string;
  own_product_id: string | null;
  own_sku: string | null;
  similarity_score: number;
  match_basis: Record<string, unknown> | null;
  diff_summary: Record<string, unknown> | null;
}

// ── agent_analyses ──────────────────────────────────────────
export interface AgentAnalysis {
  id: string;
  anomaly_id: string;
  model_version: string;
  prompt_version: string | null;
  llm_reasoning: string;
  strategy_recommendation: StrategyRecommendation | null;
  created_at: string;
}

export interface StrategyRecommendation {
  cause_hypothesis: string;
  impact_on_own: string;
  action: "price_match" | "promo_match" | "inventory_push" | "monitor";
  action_detail: string;
  priority: "high" | "medium" | "low";
  confidence: number;
}
